dist: xenial
language: java
sudo: false
jdk: openjdk14
install: true
before_install:
  - chmod +x mvnw
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
git:
  depth: false
